export default {
    af: "Afrikaans",
    sq: "Albanian",
    ar: "Arabic",
    be: "Belarusian",
    bg: "Bulgarian",
    bn: "Bengali",
    ca: "Catalan",
    zh: "Chinese",
    hr: "Croatian",
    cs: "Czech",
    da: "Danish",
    nl: "Dutch",
    en: "English",
    eo: "Esperanto",
    et: "Estonian",
    fi: "Finnish",
    fr: "French",
    gl: "Galician",
    ka: "Georgian",
    de: "German",
    el: "Greek",
    gu: "Gujarati",
    ht: "Haitian Creole",
    he: "Hebrew",
    hi: "Hindi",
    hu: "Hungarian",
    is: "Icelandic",
    id: "Indonesian",
    ga: "Irish",
    it: "Italian",
    ja: "Japanese",
    kn: "Kannada",
    ko: "Korean",
    lt: "Lithuanian",
    lv: "Latvian",
    mk: "Macedonian",
    mr: "Marathi",
    ms: "Malay",
    mt: "Maltese",
    no: "Norwegian",
    fa: "Persian",
    pl: "Polish",
    pt: "Portuguese",
    ro: "Romanian",
    ru: "Russian",
    sk: "Slovak",
    sl: "Slovenian",
    es: "Spanish",
    sv: "Swedish",
    sw: "Swahili",
    tl: "Tagalog",
    ta: "Tamil",
    te: "Telugu",
    th: "Thai",
    tr: "Turkish",
    uk: "Ukrainian",
    ur: "Urdu",
    vi: "Vietnamese",
    cy: "Welsh",

}



// export enum TranslateLanguage {
//     AFRIKAANS = 'af',
//     ALBANIAN = 'sq',
//     ARABIC = 'ar',
//     BELARUSIAN = 'be',
//     BULGARIAN = 'bg',
//     BENGALI = 'bn',
//     CATALAN = 'ca',
//     CHINESE = 'zh',
//     CROATIAN = 'hr',
//     CZECH = 'cs',
//     DANISH = 'da',
//     DUTCH = 'nl',
//     ENGLISH = 'en',
//     ESPERANTO = 'eo',
//     ESTONIAN = 'et',
//     FINNISH = 'fi',
//     FRENCH = 'fr',
//     GALICIAN = 'gl',
//     GEORGIAN = 'ka',
//     GERMAN = 'de',
//     GREEK = 'el',
//     GUJARATI = 'gu',
//     HAITIAN_CREOLE = 'ht',
//     HEBREW = 'he',
//     HINDI = 'hi',
//     HUNGARIAN = 'hu',
//     ICELANDIC = 'is',
//     INDONESIAN = 'id',
//     IRISH = 'ga',
//     ITALIAN = 'it',
//     JAPANESE = 'ja',
//     KANNADA = 'kn',
//     KOREAN = 'ko',
//     LITHUANIAN = 'lt',
//     LATVIAN = 'lv',
//     MACEDONIAN = 'mk',
//     MARATHI = 'mr',
//     MALAY = 'ms',
//     MALTESE = 'mt',
//     NORWEGIAN = 'no',
//     PERSIAN = 'fa',
//     POLISH = 'pl',
//     PORTUGUESE = 'pt',
//     ROMANIAN = 'ro',
//     RUSSIAN = 'ru',
//     SLOVAK = 'sk',
//     SLOVENIAN = 'sl',
//     SPANISH = 'es',
//     SWEDISH = 'sv',
//     SWAHILI = 'sw',
//     TAGALOG = 'tl',
//     TAMIL = 'ta',
//     TELUGU = 'te',
//     THAI = 'th',
//     TURKISH = 'tr',
//     UKRAINIAN = 'uk',
//     URDU = 'ur',
//     VIETNAMESE = 'vi',
//     WELSH = 'cy',
//   }